import LeanAideCore
import Mathlib
set_option linter.style.commandStart false
set_option linter.style.longLine false
set_option linter.unusedTactic false

/-
## Theorem:
Let $(a_n)$ be a sequence defined by $a_0=c$ and $a_{n+1} = a_n$ for all $n$.
Then $a_n = c$ for all $n$.

## Proof:
Let $(a_n)$ be a sequence defined by $a_0 = c$ and $a_{n+1} = a_n$ for all natural numbers $n$. We prove that $a_n = c$ for all $n$ by induction on $n$.

First, consider the base case $n = 0$. By the definition of the sequence, $a_0 = c$. Thus the statement holds for $n = 0$.

Next, consider the inductive step. Fix an arbitrary natural number $n$ and assume as the inductive hypothesis that $a_n = c$. We must show that $a_{n+1} = c$. By the recursive definition of the sequence, $a_{n+1} = a_n$. Using the inductive hypothesis $a_n = c$, it follows that $a_{n+1} = c$.

By the principle of mathematical induction, the equality $a_n = c$ holds for every natural number $n$.
-/

--## Structured JSON Proof

def example4 := json% {
  "document": {
    "type": "document",
    "body": [
      {
        "type": "Theorem",
        "label": "thm:constant-sequence",
        "header": "Theorem",
        "claim": "Let (a_n) be a sequence defined by a_0 = c and a_{n+1} = a_n for all n. Then a_n = c for all n.",
        "proof": {
          "type": "induction_proof",
          "on": "n",
          "base_case_proof": [
            {
              "type": "assume_statement",
              "assumption": "Consider the base case n = 0."
            },
            {
              "type": "assert_statement",
              "claim": "By the definition of the sequence, a_0 = c."
            },
            {
              "type": "conclude_statement",
              "claim": "Thus the statement a_n = c holds for n = 0."
            }
          ],
          "induction_step_proof": [
            {
              "type": "assume_statement",
              "assumption": "Fix an arbitrary natural number n and assume as the induction hypothesis that a_n = c."
            },
            {
              "type": "assert_statement",
              "claim": "By the recursive definition of the sequence, a_{n+1} = a_n."
            },
            {
              "type": "assert_statement",
              "claim": "Using the induction hypothesis a_n = c and the equality a_{n+1} = a_n, it follows that a_{n+1} = c."
            },
            {
              "type": "conclude_statement",
              "claim": "Therefore, if a_n = c, then a_{n+1} = c, completing the induction step."
            }
          ]
        }
      },
      {
        "type": "conclude_statement",
        "claim": "By the principle of mathematical induction, the equality a_n = c holds for every natural number n."
      }
    ]
  }
}

#leanaide_connect

-- ## Lean Proof generated by LeanAide

#guard_msgs in
theorem eq_const_of_succ_eq_self :
    ∀ {α : Type u} (c : α) (a : ℕ → α),
      a 0 = c → (∀ (n : ℕ), a (n + 1) = a n) → ∀ (n : ℕ), a n = c :=
  by
  intro α c a a_18193650970466190054 a_18068984259474765511 n
  induction n with
  | zero =>
    grind only
  | succ n ih =>
    grind only [#4b08]
  done
#check "Error: codegen: no valid function found for key conclude_statement"
#check "Tried functions: #[LeanAide.concludeCode]"
#check "Errors in functions:"
#check ""
#check "LeanAide.concludeCode: codegen: conclude_statement does not work for kind [commandSeq]"
#check "source:"
#check "{\"claim\":"
#check
  " \"By the principle of mathematical induction, the equality a_n = c holds for every natural number n.\"}"

/-
## Theorem:
Let $(a_n)$ be a sequence defined by $a_0=c$ and $a_{n+1} = a_n$ for all $n$.
Then $a_n = c$ for all $n$.

## A shorter proof of the same Theorem:
By induction.
Base case: $a_0=c$ by definition.
Inductive step: if $a_n=c$, then $a_{n+1}=a_n=c$.
Thus $a_n=c$ for all $n$.

-/

-- ## Structured JSON Proof

def example4' := json% {
  "document": {
    "type": "document",
    "body": [
      {
        "type": "Theorem",
        "label": "thm:constant-sequence",
        "header": "Theorem",
        "hypothesis": [
          {
            "type": "let_statement",
            "variable_name": "a_n",
            "variable_type": "sequence",
            "properties": "defined by a_0 = c and a_{n+1} = a_n for all n",
            "statement": "Let (a_n) be a sequence defined by a_0 = c and a_{n+1} = a_n for all n."
          }
        ],
        "claim": "Then a_n = c for all n.",
        "proof": {
          "type": "induction_proof",
          "on": "n",
          "base_case_proof": [
            {
              "type": "assert_statement",
              "claim": "a_0 = c",
              "proof_method": "by definition of the sequence (a_n)."
            }
          ],
          "induction_step_proof": [
            {
              "type": "assume_statement",
              "assumption": "Assume a_n = c."
            },
            {
              "type": "assert_statement",
              "claim": "a_{n+1} = c",
              "proof_method": "since a_{n+1} = a_n by definition of the sequence and a_n = c by the induction hypothesis."
            },
            {
              "type": "conclude_statement",
              "claim": "Thus a_n = c for all n."
            }
          ]
        }
      }
    ]
  }
}

-- ## Lean Proof generated by LeanAide

#guard_msgs in
theorem forall_eq_of_succ_eq_self :
      ∀ {α : Type u} (a : ℕ → α) (c : α),
        a 0 = c → (∀ (n : ℕ), a (n + 1) = a n) → ∀ (n : ℕ), a n = c :=
    by
    intro α a c a_18193650970466190054 a_18068984259474765511 n
    induction n with
    | zero =>
      grind only
    | succ n ih =>
      grind only [#4b08]
    done
