import LeanAideCore
import Mathlib
import Lean.Data.Json
import Lean
set_option linter.style.commandStart false
set_option linter.style.longLine false


/-
## Theorem:
For any real $x$,
\[
|x| =
\begin{cases}
x, & x\ge 0,\\
-x, & x<0.
⟧
## Proof:

Assume that $x$ is an arbitrary real number. To prove the theorem, it suffices to consider two cases, according to whether $x$ is nonnegative or negative.

First, suppose that $x \ge 0$. By the definition of the absolute value on $\mathbb{R}$, if a real number is greater than or equal to $0$, then its absolute value is equal to the number itself. Applying this to $x$, we obtain
\[
|x| = x
\]
whenever $x \ge 0$.

Next, suppose that $x < 0$. By the definition of the absolute value on $\mathbb{R}$, if a real number is less than $0$, then its absolute value is equal to the negation of that number. Applying this to $x$, we obtain
\[
|x| = -x
\]
whenever $x < 0$.

These are the only two possibilities for a real number $x$. Therefore, for every real $x$,
\[
|x| =
\begin{cases}
x, & x \ge 0,\\
-x, & x < 0.
\end{cases}
\]
-/

-- ## Structured JSON Proof

def example3 := json% {
  "document": {
    "type": "document",
    "body": [
      {
        "type": "Theorem",
        "label": "thm:absolute-value-piecewise",
        "header": "Theorem",
        "claim": "For any real number x, we have |x| = x if x ≥ 0, and |x| = -x if x < 0.",
        "proof": [
          {
            "type": "assume_statement",
            "assumption": "Assume that x is an arbitrary real number."
          },
          {
            "type": "condition_cases_proof",
            "condition": "x ≥ 0",
            "true_case_proof": [
              {
                "type": "assume_statement",
                "assumption": "Suppose that x ≥ 0."
              },
              {
                "type": "assert_statement",
                "claim": "By the definition of the absolute value on ℝ, if a real number is greater than or equal to 0, then its absolute value is equal to the number itself. Therefore, whenever x ≥ 0, we have |x| = x.",
                "proof_method": "Direct application of the definition of absolute value for nonnegative real numbers"
              }
            ],
            "false_case_proof": [
              {
                "type": "assume_statement",
                "assumption": "Suppose that x < 0."
              },
              {
                "type": "assert_statement",
                "claim": "By the definition of the absolute value on ℝ, if a real number is less than 0, then its absolute value is equal to the negation of that number. Therefore, whenever x < 0, we have |x| = -x.",
                "proof_method": "Direct application of the definition of absolute value for negative real numbers"
              }
            ]
          },
          {
            "type": "assert_statement",
            "claim": "For every real number x, exactly one of the conditions x ≥ 0 or x < 0 holds.",
            "proof_method": "Use the trichotomy property of real numbers specialized to 0 and x, and exclude the case x = 0 from x < 0"
          },
          {
            "type": "conclude_statement",
            "claim": "Therefore, for every real number x, we have |x| = x if x ≥ 0, and |x| = -x if x < 0."
          }
        ]
      }
    ]
  }
}

-- ## Lean Code generated by LeanAide

#guard_msgs in
theorem abs_of_piecewise : ∀ {x : ℝ}, (0 ≤ x → |x| = x) ∧ (x < 0 → |x| = -x) :=
    by
    intro x
    grind only [= abs.eq_1, = max_def, #5c79, #53e0]

-- ## Proof simplified by grind

#guard_msgs in
theorem abs_of_piecewise' : ∀ {x : ℝ}, (0 ≤ x → |x| = x) ∧ (x < 0 → |x| = -x) :=
    by
    grind
