import LeanAideCore
import Mathlib
set_option linter.style.commandStart false
set_option linter.style.longLine false

-- #leanaide_connect "http://drongo:8042"

/-
### Theorem:


### Proof:


-/

-- ### JSON Structured Proof

def := json%


-- ## LeanCode generated by LeanAide
