import LeanAideCore
import Mathlib
set_option linter.style.commandStart false
set_option linter.style.longLine false

#leanaide_connect "http://drongo:8042"

/-
### Theorem:
Let $T : V \to V$ be a linear transformation satisfying $T^2 = T$.
Prove that for all integers $n \ge 1$,
\[
T^n = T.
\]

### Proof:
Assume that $V$ is a vector space over a field and that $T : V \to V$ is a linear transformation satisfying $T^2 = T$. Let $n$ be an integer with $n \ge 1$. The goal is to prove that $T^n = T$.

The proof proceeds by induction on $n$.

First, consider the base case $n = 1$. By the definition of the $1$-st power of a linear map, one has $T^1 = T$. Thus the statement holds for $n = 1$.

Next, assume as induction hypothesis that for some integer $k \ge 1$ one has
$T^k = T$.
We need to show that
$T^{k+1} = T$.

By the definition of composition powers of a linear transformation, one has
$T^{k+1} = T^k \circ T$.
Using the induction hypothesis $T^k = T$, it follows that
$T^{k+1} = T \circ T$.
By the assumed idempotence condition $T^2 = T$, the right-hand side satisfies
$T \circ T = T^2 = T$.
Combining these equalities, one obtains
$T^{k+1} = T$.

By the principle of induction on the integer $n \ge 1$, it follows that for all integers $n \ge 1$,
$T^n = T$.

-/

-- ### JSON Structured Proof

def example23 := json% {
  "document": {
    "type": "document",
    "body": [
      {
        "type": "Theorem",
        "label": "thm:idempotent_power",
        "header": "Theorem",
        "hypothesis": [
          {
            "type": "assume_statement",
            "assumption": "V is a vector space over a field and T : V → V is a linear transformation satisfying T^2 = T."
          }
        ],
        "claim": "For all integers n ≥ 1, T^n = T.",
        "proof": [
          {
            "type": "Paragraph",
            "text": "We prove the statement by induction on the integer n ≥ 1."
          },
          {
            "type": "induction_proof",
            "on": "n",
            "base_case_proof": [
              {
                "type": "assume_statement",
                "assumption": "n = 1."
              },
              {
                "type": "assert_statement",
                "claim": "T^1 = T.",
                "proof_method": "By the definition of the first power of a linear transformation."
              },
              {
                "type": "conclude_statement",
                "claim": "The statement holds for n = 1."
              }
            ],
            "induction_step_proof": [
              {
                "type": "assume_statement",
                "assumption": "For some integer k ≥ 1, one has T^k = T.",
                "label": "IH"
              },
              {
                "type": "assert_statement",
                "claim": "T^{k+1} = T^k ∘ T.",
                "proof_method": "By the definition of composition powers of a linear transformation."
              },
              {
                "type": "assert_statement",
                "claim": "T^{k+1} = T ∘ T.",
                "proof_method": "Substituting the induction hypothesis T^k = T into T^{k+1} = T^k ∘ T.",
                "internal_references": [
                  {
                    "target_identifier": "IH"
                  }
                ]
              },
              {
                "type": "assert_statement",
                "claim": "T ∘ T = T^2 = T.",
                "proof_method": "By the assumed idempotence condition T^2 = T."
              },
              {
                "type": "conclude_statement",
                "claim": "T^{k+1} = T."
              }
            ]
          },
          {
            "type": "conclude_statement",
            "claim": "By the principle of induction, for all integers n ≥ 1, T^n = T."
          }
        ]
      }
    ]
  }
}


-- ## LeanCode generated by LeanAide
theorem pow_eq_self_of_idempotent :
      ∀ {K : Type u} {V : Type v} [inst : Field K] [inst_1 : AddCommGroup V] [inst_2 : Module K V]
        (T : V →ₗ[K] V), T ^ (2 : ℕ) = T → ∀ (n : ℕ), (1 : ℕ) ≤ n → T ^ n = T :=
    by
    intro K V inst inst_1 inst_2 T a_16360571734713782635 n a_18254028488687407628
    induction n with
    | zero => grind only
    | succ n ih => exact IsIdempotentElem.pow_succ_eq n a_16360571734713782635
    done
