import LeanAideCore
import Mathlib
set_option linter.style.commandStart false
set_option linter.style.longLine false

#leanaide_connect "http://drongo:8042"

/-
### Theorem:
If $x + \frac{1}{x} = 2$ and $x \neq 0$ then $x=1$.

### Proof:
Assume that $x$ is a real number such that $x + \dfrac{1}{x} = 2$ and $x \ne 0$.

First, multiply both sides of the equation $x + \dfrac{1}{x} = 2$ by $x$. This is allowed because $x \ne 0$. The result is
\[
x \cdot x + x \cdot \frac{1}{x} = 2 \cdot x.
\]
Simplifying each term, we obtain
\[
x^2 + 1 = 2x.
\]

Next, move all terms to the left-hand side to obtain a polynomial equation:
\[
x^2 + 1 - 2x = 0.
\]
Rewriting the left-hand side, we get
\[
x^2 - 2x + 1 = 0.
\]

Recognize that the left-hand side is a perfect square:
\[
x^2 - 2x + 1 = (x - 1)^2.
\]
Therefore, the equation becomes
\[
(x - 1)^2 = 0.
\]

Since a real square is zero if and only if the base is zero, it follows that
\[
x - 1 = 0.
\]
Hence,
\[
x = 1.
\]

This shows that any real number $x$ with $x + \dfrac{1}{x} = 2$ and $x \ne 0$ must satisfy $x = 1$.
-/

--## Structured JSON Proof

def example20 := json% {
  "document": {
    "type": "document",
    "body": [
      {
        "type": "Theorem",
        "label": "thm:x-plus-inv-eq-2",
        "header": "Theorem",
        "claim": "If x + 1/x = 2 and x ≠ 0 then x = 1.",
        "hypothesis": [
          {
            "type": "assume_statement",
            "assumption": "Let x be a real number such that x + 1/x = 2 and x ≠ 0."
          }
        ],
        "proof": [
          {
            "type": "assert_statement",
            "claim": "Multiplying both sides of the equation x + 1/x = 2 by x is allowed because x ≠ 0, and yields x·x + x·(1/x) = 2·x.",
            "calculation": {
              "type": "calculation",
              "calculation_sequence": [
                "x + 1/x = 2",
                "x·x + x·(1/x) = 2·x"
              ]
            }
          },
          {
            "type": "assert_statement",
            "claim": "Simplifying each term in x·x + x·(1/x) = 2·x gives x^2 + 1 = 2x.",
            "calculation": {
              "type": "calculation",
              "calculation_sequence": [
                "x·x + x·(1/x) = 2·x",
                "x^2 + 1 = 2x"
              ]
            }
          },
          {
            "type": "assert_statement",
            "claim": "Moving all terms to the left-hand side gives x^2 + 1 - 2x = 0.",
            "calculation": {
              "type": "calculation",
              "calculation_sequence": [
                "x^2 + 1 = 2x",
                "x^2 + 1 - 2x = 0"
              ]
            }
          },
          {
            "type": "assert_statement",
            "claim": "Rewriting x^2 + 1 - 2x in standard polynomial order gives x^2 - 2x + 1 = 0.",
            "calculation": {
              "type": "calculation",
              "calculation_sequence": [
                "x^2 + 1 - 2x = 0",
                "x^2 - 2x + 1 = 0"
              ]
            }
          },
          {
            "type": "assert_statement",
            "claim": "The polynomial x^2 - 2x + 1 factors as (x - 1)^2, so (x - 1)^2 = 0.",
            "calculation": {
              "type": "calculation",
              "calculation_sequence": [
                "x^2 - 2x + 1 = 0",
                "(x - 1)^2 = 0"
              ]
            }
          },
          {
            "type": "assert_statement",
            "claim": "Since a real square is zero if and only if its base is zero, from (x - 1)^2 = 0 we get x - 1 = 0.",
            "calculation": {
              "type": "calculation",
              "calculation_sequence": [
                "(x - 1)^2 = 0",
                "x - 1 = 0"
              ]
            }
          },
          {
            "type": "assert_statement",
            "claim": "From x - 1 = 0 it follows that x = 1.",
            "calculation": {
              "type": "calculation",
              "calculation_sequence": [
                "x - 1 = 0",
                "x = 1"
              ]
            }
          },
          {
            "type": "conclude_statement",
            "claim": "Any real number x with x + 1/x = 2 and x ≠ 0 must satisfy x = 1."
          }
        ]
      }
    ]
  }
}

-- ### LeanCode generated by LeanAide

theorem eq_one_of_add_one_div_eq_two_of_ne_zero :
      ∀ {x : ℝ}, x + (1 : ℝ) / x = (2 : ℝ) → x ≠ (0 : ℝ) → x = (1 : ℝ) :=
    by
    intro x a_12873877816864381015 a_2573840419817055610
    grind only
